# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - ./gradlew billing:assemble

  publish-billing:
    cmds:
      - ./gradlew billing:publish

  publish-mediation:
    cmds:
      - ./gradlew mediation:publish

  flutter:
    deps:
      - build
    cmds:
      - cp ./billing/build/outputs/aar/billing-release.aar ../flutter/flutter_getapp_billing/android/libs/

  upload-billing:
    cmds:
      - scp -r ./billing/build/repo/ru/ getapp.store:/var/www/repo.getapp.store/www/public/

  upload-mediation:
    deps:
      - publish-mediation
    cmds:
      - scp -r ./mediation/build/repo/ru/ getapp.store:/var/www/repo.getapp.store/www/public/

  upload-boosty:
    cmds:
      - scp -r ./boosty/build/repo/ru/ getapp.store:/var/www/repo.getapp.store/www/public/

  upload-billing:
    cmds:
      - scp -r ./billing/build/repo/ru/ getapp.store:/var/www/repo.getapp.store/www/public/

  upload-mediation:
    deps:
      - publish
    cmds:
      - scp -r ./mediation/build/repo/ru/ getapp.store:/var/www/repo.getapp.store/www/public/

  upload-boosty:
    cmds:
      - scp -r ./boosty/build/repo/ru/ getapp.store:/var/www/repo.getapp.store/www/public/