# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - ./gradlew billing:assemble

  publish:
    cmds:
      - ./gradlew billing:publish

  flutter:
    deps:
      - build
    cmds:
      - cp ./billing/build/outputs/aar/billing-release.aar ../flutter/flutter_getapp_billing/android/libs/